version: "3.8"

volumes:
  pgdata:
  staticfiles:

services:
  django_app:
    container_name: "backend"
    build: .
    restart: "unless-stopped"
    volumes:
      - staticfiles:/stocks_products/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres_db

  postgres_db:
    container_name: "postgres"
    image: "postgres:latest"
    restart: "unless-stopped"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./logs:/var/log
    environment:
      POSTGRES_DB: "ntl_docker_compose"
      POSTGRES_USER: ""
      POSTGRES_PASSWORD: ""
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ntl_stocks_products"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  nginx:
    container_name: "nginx"
    build: ./nginx
    restart: "unless-stopped"
    volumes:
      - staticfiles:/var/www/html/staticfiles
    ports:
      - "80:80"
    depends_on:
      - django_app